name: ada2
channels:
  - pytorch
  - conda-forge
  - default
  - anaconda
  - plotly
dependencies:
  - python=3.8
  - pytorch=1.7.1
  - torchvision=0.8.2
  - torchaudio=0.7.2
#  - cudatoolkit=11.0
  - cudatoolkit=10.2
  - tensorboard
  - scipy
  - pudb
  - nbstripout
  - debugpy
  - matplotlib
  - opencv
  - imageio
  - ipykernel
  - plotly
  - pandas
  - scikit-image # i2vで何故か再インストール
  - scikit-learn
  - pytorch-lightning # danbooru_tagger
  - detectron2 # pose_estimator
  - iopath
  - omegaconf
  - ipywidgets     # app
  - ipycanvas      # app
  - ipyfilechooser # app
  - pyzbar # app qrcode
  - coloredlogs # app logging
  - pip
  - pip:
    - click
    - requests
    - tqdm
    - pyspng
    - ninja
    - psutil
    - imageio-ffmpeg==0.4.3
    - ipynb
    - dotdict
    - imagesize
    - git+https://github.com/not522/ac-library-python
    - p2j # nbconvertでできなかった .py → .ipynb
    - ipyplot # 画像ビューア
    - nokogiri # 自作utility関数群
    - gradio # app
    - qrcode
    - pyzbar # sudo apt install libzbar0
    - python-twitter
    - coloredlogs
    - git+https://github.com/openai/CLIP # CLIP美的スコア
    - webdataset # CLIP美的スコア
    - datasets # CLIP美的スコア
    - pytorch-fid # ./metricsに入ってるFIDは外部で使えないので
    - clean-fid
    - pytablewriter
    - pytablereader
# vim:ts=2 sw=2