name: ada
channels:
  - pytorch
  - conda-forge
  - default
  - anaconda
  - plotly
dependencies:
  - python=3.8
  - pytorch=1.7.1
  - torchvision=0.8.2
  - torchaudio=0.7.2
#  - cudatoolkit=11.0
  - cudatoolkit=10.2
  - tensorboard
  - scipy
  - pudb
  - nbstripout
  - debugpy
  - matplotlib
  - ipywidgets
  - opencv
  - imageio
  - ipykernel
  - plotly
  - pandas
  - pip
  - pip:
    - click
    - requests
    - tqdm
    - pyspng
    - ninja
    - psutil
    - imageio-ffmpeg==0.4.3
    - ipynb
    - dotdict
    - imagesize
    - git+https://github.com/not522/ac-library-python
    - p2j # nbconvertでできなかった .py → .ipynb
# vim:ts=2 sw=2