name: ada
channels:
  - pytorch
  - conda-forge
  - default
  - anaconda
dependencies:
  - python=3.7
  - pytorch=1.7.1
  - torchvision=0.8.2
  - torchaudio=0.7.2
#  - cudatoolkit=11.0
  - cudatoolkit=10.2
  - tensorboard
  - scipy
  - pudb
  - nbstripout
  - debugpy
  - matplotlib
  - ipywidgets
  - opencv
  - pip
  - pip:
    - click
    - requests
    - tqdm
    - pyspng
    - ninja
    - psutil
    - imageio-ffmpeg==0.4.3
    - python-vivid
    - ipynb
    - dotdict
    - imagesize
# vim:ts=2 sw=2